"""att

Revision ID: 2be1b1e37ae5
Revises: 
Create Date: 2024-06-27 11:46:02.274697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be1b1e37ae5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etapa', sa.String(length=80), nullable=True),
    sa.Column('situacao', sa.Text(), nullable=False),
    sa.Column('codigo_rastreio', sa.String(length=30), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipamento', sa.String(length=80), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('acessorios', sa.String(length=200), nullable=True),
    sa.Column('fk_marca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_marca_id'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['nivel_id'], ['nivel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.String(length=50), nullable=True),
    sa.Column('item', sa.String(length=50), nullable=True),
    sa.Column('valor_unit', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('fk_tecnico_id', sa.Integer(), nullable=True),
    sa.Column('fk_cliente_id', sa.Integer(), nullable=True),
    sa.Column('fk_servico_id', sa.Integer(), nullable=True),
    sa.Column('fk_equipamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['fk_equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['fk_servico_id'], ['servico.id'], ),
    sa.ForeignKeyConstraint(['fk_tecnico_id'], ['tecnico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orcamento')
    op.drop_table('tecnico')
    op.drop_table('equipamento')
    op.drop_table('servico')
    op.drop_table('peca')
    op.drop_table('nivel')
    op.drop_table('marca')
    op.drop_table('cliente')
    # ### end Alembic commands ###
