"""att

Revision ID: cd5bd2f783d5
Revises: 2be1b1e37ae5
Create Date: 2024-06-27 12:08:04.047601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd5bd2f783d5'
down_revision = '2be1b1e37ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('equipamento_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'marca', ['marca_id'], ['id'])
        batch_op.drop_column('fk_marca_id')
        batch_op.drop_column('equipamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipamento', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('fk_marca_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('equipamento_ibfk_1', 'marca', ['fk_marca_id'], ['id'])
        batch_op.drop_column('marca_id')

    # ### end Alembic commands ###
